# Generated by Django 6.0.5 on 2026-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida / En alquiler'), ('devolucion', 'Devolución'), ('danado', 'Dañado'), ('perdido', 'Perdido'), ('fuera_uso', 'Fuera de uso')], max_length=20),
        ),
    ]
