# Generated by Django 6.0.5 on 2026-05-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='empresa_organizacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='medio_contacto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='proxima_interaccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
