# Generated by Django 6.0.5 on 2026-05-30 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_contacto_correo_electronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteraccionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medio', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('llamada', 'Llamada'), ('correo', 'Correo electrónico'), ('presencial', 'Presencial'), ('otro', 'Otro')], max_length=20)),
                ('motivo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='contactos.contacto')),
            ],
        ),
    ]
