# Generated by Django 6.0.5 on 2026-09-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosistema',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
